use "../unit-test.sml";
use "../pretty-print-engine.sml";
use "../pretty-print-parser.sml";
use "../word-patricia-map.sml";
use "test-list.sml";
use "test-pretty-print-engine.sml";
use "test-pretty-print-parser.sml";
use "test-word-patricia-map.sml";
use "call-main.sml";
